name: Terraform VM Kamatera - Destroy

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Type YES to confirm destruction of Kamatera resources"
        required: true
        default: "NO"

jobs:
  terraform_destroy:
    name: Destroy Kamatera Resources
    runs-on: ubuntu-latest

    if: ${{ github.event.inputs.confirm_destroy == 'YES' }}

    defaults:
      run:
        working-directory: infra/terraform/kamatera/vm

    env:
      KAMATERA_API_CLIENT_ID: ${{ secrets.KAMATERA_API_CLIENT_ID }}
      KAMATERA_API_SECRET: ${{ secrets.KAMATERA_API_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Restore Terraform state from backup
        run: |
          if [ -f tfstate_backup/terraform.tfstate ]; then
            cp tfstate_backup/terraform.tfstate terraform.tfstate
            echo "✅ terraform.tfstate restored"
          else
            echo "⚠️ No terraform.tfstate found in tfstate_backup"
            exit 1
          fi

          if [ -f tfstate_backup/terraform.tfstate.backup ]; then
            cp tfstate_backup/terraform.tfstate.backup terraform.tfstate.backup
            echo "✅ terraform.tfstate.backup restored"
          fi

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve

      - name: Commit updated (empty) state to repo
        run: |
          cp terraform.tfstate tfstate_backup/terraform.tfstate
          cp terraform.tfstate.backup tfstate_backup/terraform.tfstate.backup || true

          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git add tfstate_backup/*
          git commit -m "Update Terraform state after destroy [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main
